# Generated by Django 3.0.3 on 2020-04-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arxiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='paperID',
            field=models.CharField(default='PaperID', max_length=32),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='userID',
            field=models.CharField(default='USERID', max_length=32),
        ),
    ]
